#!/usr/bin/env bash
# setup.sh — StaticFDP Virtual Platform interactive setup
# ========================================================
# Part of the StaticFDP ecosystem (https://github.com/StaticFDP)
set -euo pipefail

G='\033[0;32m'; B='\033[0;34m'; Y='\033[1;33m'; R='\033[0m'

echo -e "${G}"
cat << 'EOF'
  ╔══════════════════════════════════════════════════════╗
  ║       StaticFDP Virtual Platform — setup             ║
  ║  Federated FDP discovery on static hosting           ║
  ╚══════════════════════════════════════════════════════╝
EOF
echo -e "${R}"
echo "This script writes vp-config.yaml with your deployment settings."
echo ""

# ── Q1: Platform ──────────────────────────────────────────────────────────────
echo -e "${B}Where should the Virtual Platform be hosted?${R}"
echo "  1) GitHub Pages only           (Microsoft, US jurisdiction)"
echo "  2) Codeberg Pages only         (Hetzner Frankfurt, EU jurisdiction)"
echo "  3) Both (dual-write, active-active)"
read -rp "Choice [1/2/3]: " PLATFORM_CHOICE

case "$PLATFORM_CHOICE" in
  2) PRIMARY="codeberg"; GH_ENABLED="false"; CB_ENABLED="true";;
  3) PRIMARY="both";     GH_ENABLED="true";  CB_ENABLED="true";;
  *) PRIMARY="github";   GH_ENABLED="true";  CB_ENABLED="false";;
esac

GH_REPO="OWNER/staticfdp-vp"; GH_PAGES="https://OWNER.github.io/staticfdp-vp"
CB_REPO="OWNER/staticfdp-vp"; CB_PAGES="https://OWNER.codeberg.page/staticfdp-vp"

if [[ "$GH_ENABLED" == "true" ]]; then
  echo ""; echo -e "${B}GitHub settings${R}"
  read -rp "  GitHub repo (OWNER/REPO): " GH_REPO
  GH_OWNER="${GH_REPO%%/*}"; GH_NAME="${GH_REPO##*/}"
  GH_PAGES="https://${GH_OWNER}.github.io/${GH_NAME}"
  read -rp "  GitHub Pages URL [${GH_PAGES}]: " _tmp
  GH_PAGES="${_tmp:-$GH_PAGES}"
fi

if [[ "$CB_ENABLED" == "true" ]]; then
  echo ""; echo -e "${B}Codeberg settings${R}"
  read -rp "  Codeberg repo (OWNER/REPO): " CB_REPO
  CB_OWNER="${CB_REPO%%/*}"; CB_NAME="${CB_REPO##*/}"
  CB_PAGES="https://${CB_OWNER}.codeberg.page/${CB_NAME}"
  read -rp "  Codeberg Pages URL [${CB_PAGES}]: " _tmp
  CB_PAGES="${_tmp:-$CB_PAGES}"
fi

echo ""; echo -e "${B}Virtual Platform identity${R}"
BASE_URL="$GH_PAGES"; [[ "$PRIMARY" == "codeberg" ]] && BASE_URL="$CB_PAGES"
read -rp "  Canonical public URL [${BASE_URL}]: " _tmp; BASE_URL="${_tmp:-$BASE_URL}"
read -rp "  VP title [My Virtual Platform]: " TITLE; TITLE="${TITLE:-My Virtual Platform}"
read -rp "  Publisher name [My Organisation]: " PUB_NAME; PUB_NAME="${PUB_NAME:-My Organisation}"
read -rp "  Publisher URL [https://example.org/]: " PUB_URL; PUB_URL="${PUB_URL:-https://example.org/}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/../vp-config.yaml"

cat > "$CONFIG" << YAML
# Virtual Platform Configuration
# Generated by scripts/setup.sh on $(date +%Y-%m-%d)

virtual_platform:
  title: "${TITLE}"
  base_url: ${BASE_URL}
  license: https://creativecommons.org/licenses/by/4.0/
  publisher_name: "${PUB_NAME}"
  publisher_url: ${PUB_URL}

infrastructure:
  primary: ${PRIMARY}

  github:
    enabled: ${GH_ENABLED}
    repo: ${GH_REPO}
    pages_url: ${GH_PAGES}

  codeberg:
    enabled: ${CB_ENABLED}
    repo: ${CB_REPO}
    base_url: https://codeberg.org
    pages_url: ${CB_PAGES}

aggregate:
  schedule: "40 4 * * *"
  timeout_seconds: 30
  soft_fail: true
YAML

echo ""; echo -e "${G}✓ Written: vp-config.yaml${R}"
echo ""; echo -e "${Y}Next steps:${R}"
echo "  1. Commit vp-config.yaml"
[[ "$GH_ENABLED" == "true" ]] && echo "  2. Enable GitHub Pages (Settings → Pages → Branch: main, Path: /docs)"
[[ "$CB_ENABLED" == "true" ]] && echo "  3. Enable Codeberg Pages and add FORGEJO_TOKEN secret in Woodpecker"
echo ""; echo "  Done! Register FDP Indexes by opening issues or adding YAML files to registered-indexes/."
